### ISSUE TITLE
Invite to publish to the Terraform Registry

### ISSUE THREAD

**Issue by aicarmic** [orange-cloudfoundry/terraform-provider-credhub#11]
👋  Hi there! We noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers (registry.terraform.io). We'd like to invite you to get it published, since it makes using and installing it much easier for anyone using Terraform 0.13! Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). If you need some help producing documentation, take a look at [this project](https://github.com/hashicorp/terraform-plugin-docs) which may come in handy!

Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io.

Thanks for your contributions and we look forward to seeing this provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by poblin-orange** [comment]
@psycofdj any plan on publishing ?

**Comment by psycofdj** [comment]
@poblin-orange I'd like to but time is missing

**Comment by ArthurHlt** [comment]
It is now available at https://registry.terraform.io/providers/orange-cloudfoundry/credhub/latest
