### ISSUE TITLE
Bump credhub cli code and use package management (e.g. go dep)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/terraform-provider-credhub#4]
The credhub cli version is currently vendored and I could not easily spot which version it was (as it it rebased, and not using a submodule). A package management such as [go dep](https://golang.github.io/dep/) might help. 

The credhub cli calls to fetch credentials have evolved to use the current=true option instead of the versions=1 in the [get-by-name](https://credhub-api.cfapps.io/#get-by-name) credhub api call, see https://github.com/orange-cloudfoundry/paas-templates/issues/53#issuecomment-386586095

**Comment by ArthurHlt** [comment]
i'm not sure about what you means by "as it it rebased, and not using a submodule". This project use [govendor](https://github.com/kardianos/govendor) which does works like go deps, i'm not just a big fan of config file for go deps (and as it is experimental for now, i prefer use govendor).

I did not use a version directly inside govendor and that's could be a mistake. Here find the version was possible by finding revision: https://github.com/orange-cloudfoundry/terraform-provider-credhub/blob/master/vendor/vendor.json#L14 and go to main repo with the revision (or use directly git: https://github.com/cloudfoundry-incubator/credhub-cli/commit/1a88d96dfb501da0a92b88b5ee647ebc03615b83 (from here we can see tag associated to commit, so version 1.7.5)

**Comment by gberche-orange** [comment]
@ArthurHlt sorry I had missed with vendor.json file. Thanks for the cli bump and the provider code refactoring
